# Generated by Django 3.2.5 on 2021-07-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210711_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'опрос', 'verbose_name_plural': 'опросы'},
        ),
        migrations.AlterModelOptions(
            name='poolquestion',
            options={'verbose_name': 'вопрос опроса', 'verbose_name_plural': 'вопросы опросов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'вопрос', 'verbose_name_plural': 'вопросы'},
        ),
        migrations.AlterModelOptions(
            name='userpolls',
            options={'verbose_name': 'опрос пользователя', 'verbose_name_plural': 'опросы пользователей'},
        ),
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='start_date',
            field=models.DateField(auto_now=True, verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('TEXT', 'ответ текстом'), ('SINGLE_CHOICE', 'выбор одного варианта'), ('MULTIPLY_CHOICE', 'выбор нескольких вариантов')], default='TEXT', max_length=250, verbose_name='Тип ответа'),
        ),
    ]
