# Generated by Django 3.2.5 on 2021-07-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210711_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poolquestion',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='poolquestion',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='userpolls',
            old_name='poll_id',
            new_name='poll',
        ),
        migrations.RenameField(
            model_name='userpolls',
            old_name='question_id',
            new_name='question',
        ),
    ]
