# Generated by Django 3.2.5 on 2021-07-11 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210711_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
            options={
                'verbose_name': 'ответ на вопрос',
                'verbose_name_plural': 'ответы на вопросы',
            },
        ),
        migrations.CreateModel(
            name='UserPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'опрос пользователя',
                'verbose_name_plural': 'опросы пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserPollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.answerquestion')),
                ('user_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.userpoll')),
            ],
            options={
                'verbose_name': 'ответ на вопрос опроса',
                'verbose_name_plural': 'ответы на вопросы опросов',
            },
        ),
        migrations.DeleteModel(
            name='UserPolls',
        ),
        migrations.AddField(
            model_name='userpoll',
            name='answers',
            field=models.ManyToManyField(through='polls.UserPollAnswer', to='polls.AnswerQuestion'),
        ),
        migrations.AddField(
            model_name='userpoll',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
    ]
