# Generated by Django 3.2.5 on 2021-07-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210711_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_type',
            field=models.CharField(choices=[('TEXT', 'ответ текстом'), ('SINGLE_CHOICE', 'выбор одного варианта'), ('MULTIPLY_CHOICE', 'выбор нескольких вариантов')], max_length=250, verbose_name='Тип ответа'),
        ),
    ]
